### ISSUE TITLE
Let's Collaborate

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/jubilant-octo-robot#1]
Please comment on this issue to be added as a collaborator in this repo.

**Comment by DeemsW** [comment]
Woo!

**Comment by wheatbrad** [comment]
Yaz! Lets

**Comment by anyweez** [comment]
Yessssss

**Comment by MortonBTC** [comment]
Yeahhh!

**Comment by ccgriswold** [comment]
Code Party Time!

**Comment by kyleholliday** [comment]
:8ball:

**Comment by MichaelWDanko** [comment]
whats happenin

**Comment by andrewwcaldwell** [comment]
![joe dirt 2](https://cloud.githubusercontent.com/assets/17534995/13707980/339685c6-e77a-11e5-9152-f4d388f90a9b.jpg)

**Comment by dtran2386** [comment]
sorry i'm late

**Comment by githubteacher** [comment]
:tada: @DeemsW, @wheatbrad, @anyweez, @MortonBTC, @claygrizzy, @kholliday88, @MichaelWDanko, @andrewwcaldwell, and @dtran2386 are now  repository collaborators. :balloon:
