### ISSUE TITLE
GitHubTeacher needs a bio

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/jubilant-octo-robot#2]
I think @githubteacher needs a bio.  It should have a few things:
- [ ] Name
- [ ] Occupation
- [ ] Location

**Comment by kyleholliday** [comment]
![screen shot 2016-03-11 at 11 22 19 am](https://cloud.githubusercontent.com/assets/11080502/13708290/b774b182-e77b-11e5-9385-db4e3246618d.png)
